### PR TITLE
Enable selective months disabling and style action buttons to the context's theme

### PR DESCRIPTION
**Pull request by ahmdaeyz**
Hey, 
I added selectableMonthPredicate which enables the lib user to selectively disable/enable certain dates (months in our case) just like the official date picker dialog. In addition to that, I styled the actions button row to inherit from the context's theme. This one is kind of opinionated though.

### CODE REVIEW

**Comment by Macacoazul01** [comment]
any updates on this?

**Comment by ahmdaeyz** [comment]
Thanks to @negitorogithub PR is now null safe. I resolved the conflicts between my "master" branch and this repo's. It would be nice if @hmkrivoj  gave it a look.

**Comment by Macacoazul01** [comment]
@ahmdaeyz i`m maintaining an updated version of this package, and your changes are there
https://pub.dev/packages/month_picker_dialog_2

**Comment by Macacoazul01** [comment]
closed in favor of https://github.com/hmkrivoj/month_picker_dialog/pull/52

**Pull request closed without merging**
