### PR TITLE
added background color feature and modified android folder

### PR DESCRIPTION
**Pull request by Saleh-Marji**
I added the background color feature which enables the users to edit the background color of the month picker dialog instead of it just being transparent.

I also created a new project and copied and pasted all the config folders in the example folder, so that it is updated, I guess XD.

Maybe me editing the example folder, but the rest is worth viewing.

Best Regards

Saleh Marji

### CODE REVIEW

**Comment by Saleh-Marji** [comment]
Ok.

**Comment by Macacoazul01** [comment]
@Saleh-Marji Just took some time to look for the PR. 
Gonna change some things before merging.

I'll return 10/04 so until 11 it'll be merged.

Tks.

**Comment by Saleh-Marji** [comment]
Sounds good.

**Comment by Macacoazul01** [comment]
changed a little. 
It'll be avaliable in 1.1.0

**Comment by Saleh-Marji** [comment]
Awesome, thanks!

**Pull request closed without merging**
